id = "gatito-theme"
name = "Gatito Theme"
version = "0.2.0"
schema_version = 1
authors = ["Pavel Lozinsky <pavel@lozinsky.dev>"]
description = "Zed version of the popular Gatito Theme for VSCode."
repository = "https://github.com/lozinsky/zed-gatito-theme"
