name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: false
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Publish Zed extension
        uses: huacnlee/zed-extension-action@8cd592a0d24e1e41157740f1a529aeabddc88a1b # v2.0.0
        with:
          extension-name: gatito-theme
          push-to: lozinsky/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
