name: Release and publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        required: true
        default: minor
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.write_extension.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.13.1

      - name: Read extension
        id: read_extension
        run: |
          VERSION=$(sed -n 's/version = \"\(.*\)\"/\1/p' < extension.toml)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Write extension
        id: write_extension
        run: |
          VERSION=$(npx -y semver@7.7.4 ${{ steps.read_extension.outputs.version }} -i ${{ github.event.inputs.release_type }})
          sed -i "s/^version = \"${{ steps.read_extension.outputs.version }}\"/version = \"$VERSION\"/" extension.toml
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add extension.toml
          git commit -m "chore: release v${{ steps.write_extension.outputs.version }}"
          git tag "v${{ steps.write_extension.outputs.version }}"
          git push origin HEAD --tags

      - name: Create release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: v${{ steps.write_extension.outputs.version }}
          tag_name: v${{ steps.write_extension.outputs.version }}
          generate_release_notes: true

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish Zed extension
        uses: huacnlee/zed-extension-action@8cd592a0d24e1e41157740f1a529aeabddc88a1b # v2.0.0
        with:
          extension-name: gatito-theme
          tag: v${{ needs.release.outputs.version }}
          push-to: lozinsky/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
