name: Release and publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        required: true
        default: minor
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.bump_extension.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: lts

      - name: Bump extension
        id: bump_extension
        run: |
          VERSION=$(deno eval "
            import * as toml from 'jsr:@std/toml@1.0.11';
            import * as semver from 'jsr:@std/semver@1.0.8';

            const extension = toml.parse(Deno.readTextFileSync('extension.toml'));
            extension.version = semver.format(semver.increment(semver.parse(extension.version), '${{ github.event.inputs.release_type }}'));
            Deno.writeTextFileSync('extension.toml', toml.stringify(extension));
            console.log(extension.version);
          ")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add extension.toml
          git commit -m "chore: release v${{ steps.bump_extension.outputs.version }}"
          git tag "v${{ steps.bump_extension.outputs.version }}"
          git push origin HEAD --tags

      - name: Create release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: v${{ steps.bump_extension.outputs.version }}
          tag_name: v${{ steps.bump_extension.outputs.version }}
          generate_release_notes: true

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish Zed extension
        uses: huacnlee/zed-extension-action@8cd592a0d24e1e41157740f1a529aeabddc88a1b # v2.0.0
        with:
          extension-name: gatito-theme
          tag: v${{ needs.release.outputs.version }}
          push-to: lozinsky/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
